# Numpy

NumPy is a Python package. It stands for 'Numerical Python'. It is a library consisting of 
multidimensional array objects and a collection of routines for processing of array. 
Numeric, the ancestor of NumPy, was developed by Jim Hugunin. Another package 
Numarray was also developed, having some additional functionalities. In 2005, Travis 
Oliphant created NumPy package by incorporating the features of Numarray into Numeric 
package.

In [2]:
import numpy as np

# create array and random array

In [2]:
# one dimensional array.
my_list = [1,2,3,4,5]
a = np.array(my_list)
a

array([1, 2, 3, 4, 5])

In [3]:
# tow dimensional array.
my_list_1 = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(my_list_1)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# three dimensional array.
my_list_2 = [[[1,2,3],[4,5,6],[7,8,9]]]
c = np.array(my_list_2)
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [5]:
##normal distribution
np.random.rand(5)

array([0.12110241, 0.15007109, 0.05599739, 0.09809218, 0.37005132])

In [6]:
##give me 5 random elements from 0 to 1 (5*5).
np.random.rand(5,5)

array([[0.50131853, 0.91236678, 0.86944535, 0.13380347, 0.68769723],
       [0.65825272, 0.55898383, 0.78884928, 0.29131232, 0.40117985],
       [0.80646083, 0.36850334, 0.05472778, 0.0333372 , 0.43939854],
       [0.29746086, 0.95088463, 0.52755733, 0.87539803, 0.51457653],
       [0.08282771, 0.6159241 , 0.56016866, 0.03541447, 0.52371769]])

In [7]:
##rondom integer number from 1 to 99
array=np.random.randint(1,100)
array

94

In [8]:
#rondom integer number from 1 to 99 return 25 numbers
array=np.random.randint(1,100,size=25)
array

array([27, 83, 61, 74, 16, 59, 17, 37, 57, 58, 89, 25, 51, 46, 67, 90, 72,
       87, 63, 36, 38, 98, 79,  6, 40])

In [9]:
k = np.full((3,2), 2)
print(k)

[[2 2]
 [2 2]
 [2 2]]


#  Array Attributes

In [10]:
# Get Shape.
my_list_1 = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(my_list_1)
b.shape

(3, 3)

In [11]:
# get dimension .
my_list_2 = [[[1,2,3],[4,5,6],[7,8,9]]]
c = np.array(my_list_2)
get_dimension = c.ndim
get_dimension

3

In [12]:
# Get Size.
my_list_2 = [[[1,2,3],[4,5,6],[7,8,9]]]
c = np.array(my_list_2)
c.itemsize

4

In [13]:
# Get total size.
my_list_1 = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(my_list_1)
b.nbytes

36

In [14]:
# Get Type.
my_list = [1,2,3,4,5]
a = np.array(my_list)
a.dtype

dtype('int32')

In [15]:
#shows the current values of flags.
my_list = [1,2,3,4,5]
a = np.array(my_list)
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

# Array from Numerical Ranges

In [16]:
#return an ndarray object containing evenly spaced values within a given range.
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [17]:
# In this function, instead of step size, the number of evenly spaced values between the interval is specified.
y = np.linspace(10,20,5)
y

array([10. , 12.5, 15. , 17.5, 20. ])

In [18]:
#This function returns a ndarray object that contains the numbers that are evenly spaced on a log scale.
u = np.logspace(1.0, 2.0, num=10)
u

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [19]:
# copying arrays.
my_list = [1,2,3,4,5]
a = np.array(my_list)
f = a.copy()
f

array([1, 2, 3, 4, 5])

In [3]:
# Get number of elements.
my_list_2 = [[[1,2,3],[4,5,6],[7,8,9]]]
c = np.array(my_list_2)
c.size

9

In [21]:
# get length.
my_list = [1,2,3,4,5]
a = np.array(my_list)
len(a)

5

# Array Manipulation 

In [22]:
#Reorganizing Arrays
my_list_1 = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(my_list_1)
g = b.reshape((1,9))
g

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [23]:
# returns a copy of an array collapsed into one dimension.
o = np.arange(8).reshape(2,4)
o.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [24]:
#returns a flattened one-dimensional array.
p = np.arange(8).reshape(2,4)
p.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [25]:
#This function permutes the dimension of the given array.
i = np.arange(8).reshape(2,4)
i.transpose()

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [26]:
#concatenate
my_list_3 = np.array([1, 2, 3])
my_list_4 = np.array([4, 5, 6])
k = np.concatenate((my_list_3, my_list_4))
k

array([1, 2, 3, 4, 5, 6])

In [27]:
#This function joins the sequence of arrays along a new axis.
array_1 = np.array([[1,2],[3,4]])
array_2 = np.array([[5,6],[7,8]])
np.stack((array_1,array_2),axis=1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [4]:
# Vertically stacking vectors
a_1 = np.array([1,2,3,4,5])
a_2 = np.array([6,7,8,9,10])

np.vstack([a_1,a_2])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [29]:
# Horizontal  stack
h_1 = np.ones((2,4))
h_2 = np.zeros((2,2))

np.hstack((h_1,h_2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [30]:
#This function divides the array into subarrays along a specified axis.
l = np.arange(9)
np.split(l,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [31]:
#This function adds values at the end of an input array.
a = np.array([[1,2,3],[4,5,6]])
np.append(a, [7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
#This function returns a new array with the specified subarray deleted from the input array.
m = np.arange(12).reshape(3,4)
np.delete(m,5)

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [33]:
#This function returns an array of unique elements in the input array.
a = np.array([5,2,6,2,7,5,6,8,2,9])
np.unique(a)

array([2, 5, 6, 7, 8, 9])

In [34]:
v = np.array([1, 0, 1])
array_7 = np.tile(v, (4, 1))
print(array_7)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [35]:
# returns the indices of non-zero elements in the input array.
np.nonzero (v)

(array([0, 2], dtype=int64),)

# Sort, Search & Counting Functions 

In [36]:
#Sorting means putting elements in an ordered sequence.
my_list_1 = [1,3,2,4,5]
h = np.array(my_list)
j = np.sort(h)
j

array([1, 2, 3, 4, 5])

In [37]:
#Search at array
my_list_2 = np.array([1, 2, 3, 4, 5, 3, 3])
np.where(my_list_2 == 3)

(array([2, 5, 6], dtype=int64),)

In [38]:
#These two functions return the indices of maximum and minimum elements respectively along the given axis.
w = np.array([[30,40,70],[80,20,10],[50,90,60]])
np.argmax(w)

7

In [39]:
w = np.array([[30,40,70],[80,20,10],[50,90,60]])
np.argmin(w)

5

# specific elements, rows, columns

In [40]:
my_list_1 = [[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]]
d = np.array(my_list_1)
d

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [41]:
# Get a specific element [--, --]
d [0, 0]

1

In [42]:
# Get a specific row or column
d [0, :]
d [:, 2]

array([ 3, 11])

In [43]:
# Getting a little more fancy [startindex:endindex:stepsize]
d [0, 1:-1:2]

array([2, 4, 6])

In [44]:
# Replace items
d [1,5] = 20

d [:,1] = [1,2]
d

array([[ 1,  1,  3,  4,  5,  6,  7,  8],
       [ 9,  2, 11, 12, 13, 20, 15, 16]])

# Different Types of Arrays

In [45]:
# The identity matrix
np.identity(5) #or
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
# All zeros matrix
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
# All one's matrix
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
#It creates an uninitialized array of specified shape and dtype.
q = np.empty([3,2], dtype=int)
q

array([[1611517584,        602],
       [         0,          0],
       [    131074,        293]])

In [49]:
# Repeat an array
my_list_5 = np.array([[1,2,3,4,5]])
e = np.repeat(my_list_5,3, axis=0) # or (axis=0 for rows)
e

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [50]:
# Any other number
np.full((5,5), 100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

# Statistics

In [51]:
my_list_5=np.arange(20)
my_list_5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [52]:
#return the minimum from the elements
np.min(my_list_5)

0

In [53]:
#return the maximum from the elements
np.max(my_list_5)

19

In [54]:
#returns the range (maximum-minimum) of values along with an axis.
my_list_1 = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(my_list_1)
np.ptp(b)

8

In [55]:
#Percentile is a measure used in statistics indicating the value below which a given percentage of observations in a group of observations fall.
my_list_1 = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(my_list_1)
np.percentile(b, 70, axis=1)

array([2.4, 5.4, 8.4])

In [56]:
my_list_1 = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(my_list_1)
np.median(b)

5.0

In [57]:
my_list_1 = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(my_list_1)
np.mean(b)

5.0

In [58]:
my_list_1 = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(my_list_1)
np.average(b)

5.0

In [59]:
# std is the square root of the average squared deviations from mean.
my_list = [1,2,3,4,5]
a = np.array(my_list)
np.std(a)

1.4142135623730951

In [60]:
#Variance is the average of squared deviations
my_list = [1,2,3,4,5]
a = np.array(my_list)
np.var(a)

2.0

In [61]:
my_list = [1,2,3,4,5]
a = np.array(my_list)
np.cov(a)

array(2.5)

# Mathematical Functions

In [62]:
z = np.array([20,30,45,60,90])
np.sin(z)

array([ 0.91294525, -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [63]:
np.cos(z)

array([ 0.40808206,  0.15425145,  0.52532199, -0.95241298, -0.44807362])

In [64]:
np.tan(z)

array([ 2.23716094, -6.4053312 ,  1.61977519,  0.32004039, -1.99520041])

In [65]:
np.log(z)

array([2.99573227, 3.40119738, 3.80666249, 4.09434456, 4.49980967])

In [66]:
np.sqrt(z)

array([4.47213595, 5.47722558, 6.70820393, 7.74596669, 9.48683298])

In [67]:
np.exp(z)

array([4.85165195e+08, 1.06864746e+13, 3.49342711e+19, 1.14200739e+26,
       1.22040329e+39])

#  Arithmetic Operations

In [68]:
array_3 = np.array([10, 20, 30, 40, 50, 60])
array_4 = np.array([20, 21, 22, 23, 24, 25])

In [69]:
np.add(array_3,array_4)

array([30, 41, 52, 63, 74, 85])

In [70]:
np.subtract(array_3,array_4)

array([-10,  -1,   8,  17,  26,  35])

In [71]:
np.multiply(array_3,array_4)

array([ 200,  420,  660,  920, 1200, 1500])

In [72]:
np.divide(array_3,array_4)

array([0.5       , 0.95238095, 1.36363636, 1.73913043, 2.08333333,
       2.4       ])

In [73]:
array_3**2

array([ 100,  400,  900, 1600, 2500, 3600], dtype=int32)

In [74]:
array_3=array_4
array_3

array([20, 21, 22, 23, 24, 25])

In [75]:
array_3>5

array([ True,  True,  True,  True,  True,  True])

In [76]:
array_3[array_3>5]

array([20, 21, 22, 23, 24, 25])

# Linear Algebra

In [77]:
#Dot product of the two arrays.
np.dot(array_3,array_4)

3055

In [78]:
#Dot product of the two vectors.
np.vdot(array_3,array_4)

3055

In [83]:
#Matrix product of the two arrays.
a = [[1,0],[0,1]]
b = [[4,1],[2,2]]
np.matmul(a,b)

array([[4, 1],
       [2, 2]])

In [80]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# Miscellaneous

Load Data from File

In [8]:
#Load Data from File.
filedata = np.genfromtxt('data.txt')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [12]:
#Load Data from File.
filedata_1 = np.loadtxt('data.txt', dtype='int32')
filedata_1

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

Boolean Masking and Advanced Indexing

In [7]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [13]:
filedata[(~((filedata > 50) & (filedata < 100)))]

array([  1,  13,  21,  11, 196,   4,   3,  34,   6,   7,   8,   0,   1,
         2,   3,   4,   5,   3,  42,  12,  33, 766,   4,   6,   4,   3,
         4,   5,   6,   7,   0,  11,  12,   1,  22,  33,  11, 999,  11,
         2,   1,   0,   1,   2,   9,   8,   7,   1])

# With best wishes